### ISSUE TITLE
Define the sink without reference to the bin mapper

### ISSUE THREAD

**Issue by jpthompson17** [westpa/westpa#467]
## Is your feature request related to a problem? Please describe

Currently, the definition of the sink depends on the bin mapper (i.e., the sink is the union of bins containing target states). This dependence complicates the use of adaptive binning methods in nonequilibrium steady state simulations, since it's usually desirable for the sink to remain constant during the simulation. (A current solution is to [embed the adaptive bin mapper in a recursive bin mapper with a fixed base mapper](https://github.com/westpa/westpa2_tutorials/blob/2640a38f0f104060151717a1bcea443ffff3ff66/tutorial7.6-membrane/west.cfg#L36), but this feels a bit clunky to me.) Moreover, the dependence on the bin mapper unnecessarily couples *recycling* to *resampling*, and gets in the way of implementing truly binless resampling methods.

## Describe the solution you'd like

Instead of defining the sink indirectly via a bin mapper and one or more target states:

`west.cfg`:
```yaml
      bins:
        type: RectilinearBinMapper
        boundaries:         
          - [0.0, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, .inf]
```
`tstate.file`:
```
unfolded 4.02
```

I'd like to be able to define the sink directly by specifying a region in progress coordinate space, e.g.,

`west.cfg`:
```yaml
      sink: 'x: x[0] > 4.0'
```
